name: Cyrosamba_Formatter

on: [push, pull_request, fork]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install -r requirements.txt
      - name: Lint with Ruff
        run: |
          pip3 install ruff
          ruff --output-format=github .
        continue-on-error: true
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Run black formatter
        run: |
          pip3 install black
          black --check .        
    test:
      runs-on: ubuntu-latest
      strategy:
        matrix:
          python-version: ['3.9', '3.11']
      steps:
        - uses: actions/checkout@v4
        - name: Setup Python ${{matrix.python-version}}
          uses: actions/setup-python@v5
          with:
            python-version: ${{matrix.python-version}}
        - name: Install dependencies
          run: | 
            python3 -m pip install --upgrade pip
            pip3 install -r requirements.txt
        - name: Install tox and any other packages
          run: pip3 install tox
        - name: Run tox
          run: tox -e py
