name: Cyrosamba_Formatter

on: [push, pull_request, fork]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install -r requirements.txt
      - name: Lint with Ruff
        run: |
          pip3 install ruff
          ruff --output-format=github .
        continue-on-error: true

  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install Black
        run: |
          pip3 install black
      - name: Run Black formatter
        id: black
        run: |
          black .
      - name: Commit changes
        if: ${{ steps.black.outcome == 'success' }}
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add .
          git commit -m "Auto-format code with Black"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
